### PR TITLE
Feat update packages

### PR DESCRIPTION
**Pull request by omitobi**

### CODE REVIEW

**Comment by arietimmerman** [comment]
Awesome. Looks really good.
Would you mind adding `lcobucci/jwt` to the `composer.json`, since you have effectively upgraded that package.
 
See: https://github.com/arietimmerman/openid-connect-server/pull/27#issuecomment-1725015086

**Comment by arietimmerman** [comment]
I created a pull request with - in my opinion - a fix. The rest looks great.
https://github.com/eideasy/openid-connect-server/pull/1

**Comment by omitobi** [comment]
I merged in the fix you made. Its better to exclude the registered claims from `extra`

**Comment by arietimmerman** [comment]
Thanks!

**Pull request merged**
